services:
  - type: web
    name: crysnova-ai
    repo: https://github.com/crysnovax/CRYSNOVA_AI
    branch: main
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm ci --omit=dev
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
      - key: PORT
        value: 3000
    healthCheckPath: /
